### ISSUE TITLE
Run dependency check on travis

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/autolabcli#107]
### Description

In order to actively track the dependencies, we can run the following checks on travis.
```shell
npm outdated || : 
npm-check || :    #bypass failure of npm-check
```

**Comment by mukkachaitanya** [comment]
Should I give a quick PR sir? Or we'll keep this for the new inductees?

**Comment by prasadtalasila** [comment]
Please go ahead and add this.

**Comment by mukkachaitanya** [comment]
I am adding both of them to the `npm scripts` and then to the `travis.yml`

**Comment by prasadtalasila** [comment]
The script runs as expected and shows the need for major upgrades of dependencies. When would be the right time to perform these upgrades?

**Comment by mukkachaitanya** [comment]
I'm not sure. I think it can go with this PR. But should I give this a priority or get the validation done and then move on to complete this PR?

**Comment by prasadtalasila** [comment]
Ok. Please go ahead with the validation part. In the mean time, I will also check the ramifications / advantages of moving to the latest caporal package. Till then, we can leave this PR open. Thanks.

**Comment by mukkachaitanya** [comment]
Sure sir!

**Comment by prasadtalasila** [comment]
I checked the updated to caporal.js. The updates change the color library and minor security fixes. It is worth updating the caporal.js to the latest version. As far as I can read, the binary compatibility with the old versions has been maintained.

**Comment by prasadtalasila** [comment]
Taken care of in PR #108.
