### ISSUE TITLE
use strict mode of ES6

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/autolabcli#93]
### Description

The present code base uses `eval` as module name. On the other hand `eval()` is a [built-in function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) in ES6. Such mistakes can be caught by using `use strict` directive at the top of all the modules.

### Steps to Reproduce
The problem is in the code base. Please see [controller/eval.js](https://github.com/AutolabJS/autolabcli/blob/dev/lib/controller/eval.js) and all its dependencies.

**Expected behavior:**
We should not use reserved  function names as module names.

### Additional Information
1. Rename all `eval.js` modules to `evaluate.js`.
2. Such mistakes can be caught by using `use strict` directive at the top of all the modules.

**Comment by prasadtalasila** [comment]
@mukkachaitanya This issue can be addressed in the next PR.

**Comment by mukkachaitanya** [comment]
This has been taken care of in #96
