### ISSUE TITLE
Move magic values from prefs.js to config file.

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/autolabcli#94]
### Description
The [prefs.js](https://github.com/AutolabJS/autolabcli/blob/7d700c5ad3145f67670b9fe258d73caf817563f9/lib/cli/output/prefs.js) contains magic integer and string constants. Please see the code given below.
````javascript

const showPrefs = (prefs) => {
  const table = new Table({
    head: [chalk.cyan('Preferences'), chalk.cyan('Values')],
    colWidths: [25, 27],
  });
  table.push(
    ['Gitlab host', prefs.gitlab_host],
    ['Main Server host', prefs.mainserver_host],
    ['Main Server port', prefs.mainserver_port],
    ['Logger file MaxSize', prefs.logger_size],
    ['Log file Directory', prefs.logger_dir],
    ['Log file name', prefs.logger_location],
    ['Logger blacklist keys', prefs.logger_blacklist],
);
````

### Suggested Refactoring
At least the configuration values of chalk should go to config file. The rows of the table indicating the names of different config parameters can be read from the config file itself. Of course, we may need to restructure the config file in order to achieve this effect.

**Comment by mukkachaitanya** [comment]
Sir, should I address this in the current PR?

**Comment by prasadtalasila** [comment]
Nope. Please postpone this issue to next PR.

**Comment by prasadtalasila** [comment]
Not a priority right now.
