### ISSUE TITLE
add quality check command to npm

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/autolabcli#96]
### Description

The package.json file does not include npm command for the quality checks typically done by codeclimate. Having an npm command allows us to run the code quality analysis on the local developer machines as well.

**Expected behavior:** [What you expect to happen]
````shell
npm quality
````
command is available and runs code quality checks on the code base.

**Actual behavior:** [What actually happens]
There is no command at present.

**Reproduces how often:** [What percentage of the time does it reproduce?]
All the time.

### Additional Information
We can perform code quality checks using the following tools: eslint, [jsinspect](https://github.com/danielstjules/jsinspect) and [buddy.js](https://github.com/danielstjules/buddy.js)

**Comment by mukkachaitanya** [comment]
This can be closed.
